// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	Deadline    sql.NullTime   `json:"deadline"`
	UserID      uuid.UUID      `json:"userId"`
	CreatedAt   time.Time      `json:"createdAt"`
	CreatedBy   uuid.UUID      `json:"createdBy"`
	UpdatedAt   sql.NullTime   `json:"updatedAt"`
	UpdatedBy   uuid.NullUUID  `json:"updatedBy"`
	DeletedAt   sql.NullTime   `json:"deletedAt"`
	DeletedBy   uuid.NullUUID  `json:"deletedBy"`
}

type User struct {
	ID        uuid.UUID     `json:"id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Password  string        `json:"password"`
	CreatedAt time.Time     `json:"createdAt"`
	UpdatedAt sql.NullTime  `json:"updatedAt"`
	UpdatedBy uuid.NullUUID `json:"updatedBy"`
	DeletedAt sql.NullTime  `json:"deletedAt"`
	DeletedBy uuid.NullUUID `json:"deletedBy"`
}
