// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	GetTask(ctx context.Context, id uuid.UUID) (Task, error)
	GetTasksNearDeadline(ctx context.Context, dollar_1 interface{}) ([]Task, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListTasks(ctx context.Context) ([]Task, error)
	ListTasksByPriority(ctx context.Context, priority string) ([]Task, error)
	ListTasksByStatus(ctx context.Context, status string) ([]Task, error)
	ListTasksByUser(ctx context.Context, userID uuid.UUID) ([]Task, error)
	MarkTaskAsCompleted(ctx context.Context, arg MarkTaskAsCompletedParams) (int64, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
