// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id, title, description, status, priority, deadline, user_id, created_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, title, description, status, priority, deadline, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateTaskParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	Deadline    sql.NullTime   `json:"deadline"`
	UserID      uuid.UUID      `json:"userId"`
	CreatedAt   time.Time      `json:"createdAt"`
	CreatedBy   uuid.UUID      `json:"createdBy"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Deadline,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Deadline,
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
UPDATE tasks SET
    deleted_at = NOW(),
    deleted_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type DeleteTaskParams struct {
	DeletedBy uuid.NullUUID `json:"deletedBy"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTask, arg.DeletedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, status, priority, deadline, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tasks
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Deadline,
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getTasksNearDeadline = `-- name: GetTasksNearDeadline :many
SELECT id, title, description, status, priority, deadline, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tasks
WHERE deleted_at IS NULL
AND status != 'done'
AND deadline IS NOT NULL
AND deadline <= NOW() + INTERVAL '1 hour' * $1
ORDER BY deadline ASC
`

func (q *Queries) GetTasksNearDeadline(ctx context.Context, dollar_1 interface{}) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksNearDeadline, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Deadline,
			&i.UserID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, status, priority, deadline, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tasks
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Deadline,
			&i.UserID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByPriority = `-- name: ListTasksByPriority :many
SELECT id, title, description, status, priority, deadline, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tasks
WHERE priority = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByPriority(ctx context.Context, priority string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByPriority, priority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Deadline,
			&i.UserID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByStatus = `-- name: ListTasksByStatus :many
SELECT id, title, description, status, priority, deadline, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tasks
WHERE status = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByStatus(ctx context.Context, status string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Deadline,
			&i.UserID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT id, title, description, status, priority, deadline, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM tasks
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByUser(ctx context.Context, userID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Deadline,
			&i.UserID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskAsCompleted = `-- name: MarkTaskAsCompleted :execrows
UPDATE tasks SET
    status = 'done',
    updated_at = NOW(),
    updated_by = $1
WHERE id = $2 AND deleted_at IS NULL
`

type MarkTaskAsCompletedParams struct {
	UpdatedBy uuid.NullUUID `json:"updatedBy"`
	ID        uuid.UUID     `json:"id"`
}

func (q *Queries) MarkTaskAsCompleted(ctx context.Context, arg MarkTaskAsCompletedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markTaskAsCompleted, arg.UpdatedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    title = $1,
    description = $2,
    status = $3,
    priority = $4,
    deadline = $5,
    updated_at = $6,
    updated_by = $7
WHERE id = $8 AND deleted_at IS NULL
RETURNING id, title, description, status, priority, deadline, user_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateTaskParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    string         `json:"priority"`
	Deadline    sql.NullTime   `json:"deadline"`
	UpdatedAt   sql.NullTime   `json:"updatedAt"`
	UpdatedBy   uuid.NullUUID  `json:"updatedBy"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Deadline,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Deadline,
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
